export const TRANSACTION_LAST_LIST_REQUEST='TRANSACTION_LAST_LIST_REQUEST';
export const TRANSACTION_LAST_LIST_SUCCESS='TRANSACTION_LAST_LIST_SUCCESS';
export const TRANSACTION_LAST_LIST_FAIL='TRANSACTION_LAST_LIST_FAIL';

export const JOURNAL_LIST_REQUEST='JOURNAL_LIST_REQUEST';
export const JOURNAL_LIST_SUCCESS='JOURNAL_LIST_SUCCESS';
export const JOURNAL_LIST_FAIL='JOURNAL_LIST_FAIL';

export const TRANSACTION_PERIOD_LIST_REQUEST='TRANSACTION_PERIOD_LIST_REQUEST';
export const TRANSACTION_PERIOD_LIST_SUCCESS='TRANSACTION_PERIOD_LIST_SUCCESS';
export const TRANSACTION_PERIOD_LIST_FAIL='TRANSACTION_PERIOD_LIST_FAIL';

export const CATEGORY_LIST_REQUEST='CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS='CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL='CATEGORY_LIST_FAIL';

export const ADD_TRANSACTION_REQUEST='ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_SUCCESS='ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAIL='ADD_TRANSACTION_FAIL';

export const JOURNAL_BY_SECTION_REQUEST='JOURNAL_BY_SECTION_REQUEST';
export const JOURNAL_BY_SECTION_SUCCESS='JOURNAL_BY_SECTION_SUCCESS';
export const JOURNAL_BY_SECTION_FAIL='JOURNAL_BY_SECTION_FAIL';