export const TRANSACTION_LAST_LIST_REQUEST='TRANSACTION_LAST_LIST_REQUEST';
export const TRANSACTION_LAST_LIST_SUCCESS='TRANSACTION_LAST_LIST_SUCCESS';
export const TRANSACTION_LAST_LIST_FAIL='TRANSACTION_LAST_LIST_FAIL';

export const JOURNAL_LIST_REQUEST='JOURNAL_LIST_REQUEST';
export const JOURNAL_LIST_SUCCESS='JOURNAL_LIST_SUCCESS';
export const JOURNAL_LIST_FAIL='JOURNAL_LIST_FAIL';