export const TRANSACTION_LAST_LIST_REQUEST='TRANSACTION_LAST_LIST_REQUEST';
export const TRANSACTION_LAST_LIST_SUCCESS='TRANSACTION_LAST_LIST_SUCCESS';
export const TRANSACTION_LAST_LIST_FAIL='TRANSACTION_LAST_LIST_FAIL';

export const JOURNAL_LIST_REQUEST='JOURNAL_LIST_REQUEST';
export const JOURNAL_LIST_SUCCESS='JOURNAL_LIST_SUCCESS';
export const JOURNAL_LIST_FAIL='JOURNAL_LIST_FAIL';

export const TRANSACTION_PERIOD_LIST_REQUEST='TRANSACTION_PERIOD_LIST_REQUEST';
export const TRANSACTION_PERIOD_LIST_SUCCESS='TRANSACTION_PERIOD_LIST_SUCCESS';
export const TRANSACTION_PERIOD_LIST_FAIL='TRANSACTION_PERIOD_LIST_FAIL';

export const CATEGORY_LIST_REQUEST='CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS='CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL='CATEGORY_LIST_FAIL';

export const TRANSACTION_TYPES_REQUEST='TRANSACTION_TYPES_REQUEST';
export const TRANSACTION_TYPES_SUCCESS='TRANSACTION_TYPES_SUCCESS';
export const TRANSACTION_TYPES_FAIL='TRANSACTION_TYPES_FAIL';

export const SECTION_LIST_REQUEST='SECTION_LIST_REQUEST';
export const SECTION_LIST_SUCCESS='SECTION_LIST_SUCCESS';
export const SECTION_LIST_FAIL='SECTION_LIST_FAIL';

export const FILTER_LIST_REQUEST='FILTER_LIST_REQUEST';
export const FILTER_LIST_SUCCESS='FILTER_LIST_SUCCESS';
export const FILTER_LIST_FAIL='FILTER_LIST_FAIL';

export const WALLET_LIST_REQUEST='WALLET_LIST_REQUEST';
export const WALLET_LIST_SUCCESS='WALLET_LIST_SUCCESS';
export const WALLET_LIST_FAIL='WALLET_LIST_FAIL';

export const GROUP_LIST_REQUEST='GROUP_LIST_REQUEST';
export const GROUP_LIST_SUCCESS='GROUP_LIST_SUCCESS';
export const GROUP_LIST_FAIL='GROUP_LIST_FAIL';

export const ADD_TRANSACTION_REQUEST='ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_SUCCESS='ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAIL='ADD_TRANSACTION_FAIL';
export const ADD_TRANSACTION_RESET='ADD_TRANSACTION_RESET';

export const JOURNAL_BY_SECTION_REQUEST='JOURNAL_BY_SECTION_REQUEST';
export const JOURNAL_BY_SECTION_SUCCESS='JOURNAL_BY_SECTION_SUCCESS';
export const JOURNAL_BY_SECTION_FAIL='JOURNAL_BY_SECTION_FAIL';

export const CATEGORIES_BY_SECTION_REQUEST='CATEGORIES_BY_SECTION_REQUEST';
export const CATEGORIES_BY_SECTION_SUCCESS='CATEGORIES_BY_SECTION_SUCCESS';
export const CATEGORIES_BY_SECTION_FAIL='CATEGORIES_BY_SECTION_FAIL';

export const ANALYTICS_REQUEST='ANALYTICS_REQUEST';
export const ANALYTICS_SUCCESS='ANALYTICS_SUCCESS';
export const ANALYTICS_FAIL='ANALYTICS_FAIL';