export const USER_SIGN_REQUEST = 'USER_SIGN_REQUEST';
export const USER_SIGN_SUCCESS = 'USER_SIGN_SUCCESS';
export const USER_SIGN_FAIL = 'USER_SIGN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const ADD_ACCOUNTANT_REQUEST='ADD_ACCOUNTANT_REQUEST';
export const ADD_ACCOUNTANT_SUCCESS='ADD_ACCOUNTANT_SUCCESS';
export const ADD_ACCOUNTANT_FAIL='ADD_ACCOUNTANT_FAIL';
export const ADD_ACCOUNTANT_RESET='ADD_ACCOUNTANT_RESET';

export const NEW_COUNTERPARTY_REQUEST='NEW_COUNTERPARTY_REQUEST';
export const NEW_COUNTERPARTY_SUCCESS='NEW_COUNTERPARTY_SUCCESS';
export const NEW_COUNTERPARTY_FAIL='NEW_COUNTERPARTY_FAIL';
export const NEW_COUNTERPARTY_RESET='NEW_COUNTERPARTY_RESET';

export const CHANGE_PASSWORD_REQUEST='CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL='CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_RESET='CHANGE_PASSWORD_RESET';