export const USER_SIGN_REQUEST = 'USER_SIGN_REQUEST';
export const USER_SIGN_SUCCESS = 'USER_SIGN_SUCCESS';
export const USER_SIGN_FAIL = 'USER_SIGN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';